sudo: false
dist: precise

language: php
php:
  - '7.1'

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql

env:
  global:
    - APP_DEBUG=true
    - DB_HOST=localhost
    - DB_DATABASE=sklep_sms_test
    - DB_USERNAME=root
    - DB_PASSWORD=

before_install:
  - composer self-update
  - mysql -e 'CREATE DATABASE sklep_sms_test;'

install:
  - composer install --no-interaction
  - php artisan test:setup

before_deploy:
  - rm -Rf vendor
  - composer install --no-dev --no-interaction --prefer-dist
  - |
   zip -r \
   --exclude='.git*' \
   --exclude='tests/*' \
   --exclude='docker-compose.yml' \
   --exclude='docker/*' \
   --exclude='data/cache/**' \
   --exclude='data/transfers/**' \
   --exclude='errors/**' \
   --exclude='phpunit.xml' \
   --exclude='.travis.yml' \
   --exclude='composer.json' \
   --exclude='composer.lock' \
   --exclude='README.md' \
   build.zip .

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: build.zip
  skip_cleanup: true
  on:
    tags: true
